services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: cd app && pip install -r requirements.txt
    startCommand: cd app && PYTHONPATH=./app uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: SUPABASE_URL
        value: your_value
      - key: SUPABASE_KEY
        value: your_value
